### ISSUE TITLE
Support short and long flags in `to_curl/2`

### ISSUE THREAD

**Issue by kevinschweikert** [derekkraan/curl_req#8]
When we generate the curl command we currently only use the short flags. It would be nice to let the user choose if they want the short form or the long form.

Something like:

```elixir
req |> to_curl(flags: :long)
"curl --request GET example.com"

# by default it uses the short flags
req |> to_curl()
"curl -X GET example.com"

# would be the same as
req |> to_curl(flags: :short)
"curl -X GET example.com"
```

**Comment by derekkraan** [comment]
I am also in agreement here and would accept a PR that implements this feature.
